project_id = "ohxtavjababtrcrkgndq"

[functions.get-exchange-rate]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false

[functions.submit-application]
verify_jwt = false

[functions.score-cv]
verify_jwt = false

[functions.bulk-upload-cv]
verify_jwt = true

[functions.send-interview-invite]
verify_jwt = true

[functions.send-applicant-email]
verify_jwt = true

[functions.process-scheduled-emails]
verify_jwt = false
